# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3bb5dfdc5b268c3340742a903ee19341e6e919f1a954b0c9e8f73fd4fd2186639bfbe52370adbea57f2a21769e5ccf0fe25372e04add34bb471c5e5d46720ad

test:
  secret_key_base: 3d3b2290529efaa8d2f6a08177c42f87e6bb555dc64fc437a291bd589a5e31e64a24a2b40d8899dfcdee70e69cf168ddaaeab7f8dd63c5f969af182cdbb1c742

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
